<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DiscaScout.Scraping/DiscaScout.Scraping.csproj" />
    <ProjectReference Include="../DiscaScout.Persistence/DiscaScout.Persistence.csproj" />
  </ItemGroup>
</Project>
