// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DiscaScout.Persistence.Migrations;

[DbContext(typeof(DiscaScoutDbContext))]
[Migration("20260830090000_AddScrapeAnomalyGuard")]
partial class AddScrapeAnomalyGuard
{
    protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        ScrapeAnomalyGuardModelBuilder.Build(modelBuilder);
    }
}
