// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DiscaScout.Persistence.Migrations;

[DbContext(typeof(DiscaScoutDbContext))]
[Migration("20260830000000_AddDiscordNotificationSettings")]
partial class AddDiscordNotificationSettings
{
    protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        DiscordNotificationSettingsModelBuilder.Build(modelBuilder);
    }
}
