// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DiscaScout.Persistence.Migrations;

[DbContext(typeof(DiscaScoutDbContext))]
[Migration("20260830000000_AddDiscordNotificationSettings")]
partial class AddDiscordNotificationSettings
{
    protected override void BuildTargetModel(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // モデル全体のSnapshotは別ファイルで管理する。Migration識別情報を明示して実行順を保証する。
    }
}
